package com.tax.tableentities;

import java.sql.Timestamp;

/**
 * ScpdUserDetails generated by hbm2java
 */
public class UserDetails implements java.io.Serializable {

    private Integer entityId;
    private String firstName;
    private String middleName;
    private String lastName;
    private String dateOfBirth;
    private String dateOfJoining;
    private int activeStatus;
    private Timestamp createDt;
    private Timestamp updateDt;
    private byte[] identityAttachment;

    public Integer getEntityId() {
        return entityId;
    }

    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getDateOfJoining() {
        return dateOfJoining;
    }

    public void setDateOfJoining(String dateOfJoining) {
        this.dateOfJoining = dateOfJoining;
    }

    public int getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(int activeStatus) {
        this.activeStatus = activeStatus;
    }

    public Timestamp getCreateDt() {
        return createDt;
    }

    public void setCreateDt(Timestamp createDt) {
        this.createDt = createDt;
    }

    public Timestamp getUpdateDt() {
        return updateDt;
    }

    public void setUpdateDt(Timestamp updateDt) {
        this.updateDt = updateDt;
    }

    public byte[] getIdentityAttachment() {
        return identityAttachment;
    }

    public void setIdentityAttachment(byte[] identityAttachment) {
        this.identityAttachment = identityAttachment;
    }

    
}
