package com.tax.tableentities;

import java.sql.Timestamp;

/**
 * ScpdUserDetails generated by hbm2java
 */
public class UserTransactionPayment implements java.io.Serializable {

    private Integer paymentId;
    private Integer transactionId;
    private Timestamp transactionDate;
    private double transactionAmt;
    private String orderId;
    private String bankTransactionNo;
    private double bankAmt;
    private int bankVerified;
    private int activeStatus;
    private Timestamp createDt;

    public Integer getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    public Integer getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    public Timestamp getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(Timestamp transactionDate) {
        this.transactionDate = transactionDate;
    }

    public double getTransactionAmt() {
        return transactionAmt;
    }

    public void setTransactionAmt(double transactionAmt) {
        this.transactionAmt = transactionAmt;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getBankTransactionNo() {
        return bankTransactionNo;
    }

    public void setBankTransactionNo(String bankTransactionNo) {
        this.bankTransactionNo = bankTransactionNo;
    }

    public double getBankAmt() {
        return bankAmt;
    }

    public void setBankAmt(double bankAmt) {
        this.bankAmt = bankAmt;
    }

    public int getBankVerified() {
        return bankVerified;
    }

    public void setBankVerified(int bankVerified) {
        this.bankVerified = bankVerified;
    }

    public int getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(int activeStatus) {
        this.activeStatus = activeStatus;
    }

    public Timestamp getCreateDt() {
        return createDt;
    }

    public void setCreateDt(Timestamp createDt) {
        this.createDt = createDt;
    }

    public Timestamp getUpdateDt() {
        return updateDt;
    }

    public void setUpdateDt(Timestamp updateDt) {
        this.updateDt = updateDt;
    }

    private Timestamp updateDt;

}
