package com.tax.tableentities;

import java.sql.Timestamp;

/**
 * ScpdUserDetails generated by hbm2java
 */
public class UserTransaction implements java.io.Serializable {

    private Integer transactionId;
    private Integer userId;
    private String transactionIsStr;
    private String panNo;
    private String adhaarNo;
    private String mobileNo;
    private int activeStatus;
    private Timestamp createDt;
    private Timestamp updateDt;

    public Integer getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getTransactionIsStr() {
        return transactionIsStr;
    }

    public void setTransactionIsStr(String transactionIsStr) {
        this.transactionIsStr = transactionIsStr;
    }

    public String getPanNo() {
        return panNo;
    }

    public void setPanNo(String panNo) {
        this.panNo = panNo;
    }

    public String getAdhaarNo() {
        return adhaarNo;
    }

    public void setAdhaarNo(String adhaarNo) {
        this.adhaarNo = adhaarNo;
    }

    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public int getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(int activeStatus) {
        this.activeStatus = activeStatus;
    }

    public Timestamp getCreateDt() {
        return createDt;
    }

    public void setCreateDt(Timestamp createDt) {
        this.createDt = createDt;
    }

    public Timestamp getUpdateDt() {
        return updateDt;
    }

    public void setUpdateDt(Timestamp updateDt) {
        this.updateDt = updateDt;
    }

}
